repos:
  - repo: local
    hooks:
      - id: docker-push
        name: Push image to docker hub
        entry: ./docker-push.sh
        language: system
        stages: [ pre-push ]
      - id: bump version patch
        name: Bumps version patch section
        entry: ./bump-version.sh
        language: system
        stages: [ pre-commit ]
