repos:
  - repo: local
    hooks:
      - id: docker-push
        name: Push image to docker hub
        entry: ./git-hooks/docker-push.sh
        language: system
        stages: [ push ]
      - id: bump version patch
        name: Bumps version patch section
        entry: ./git-hooks/bump-version.sh
        language: system
        stages: [ commit ]
