# Generated by Django 4.2.15 on 2024-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.AlterField(
            model_name='workout',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
