# Generated by Django 4.2.15 on 2024-12-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='duration',
            new_name='duration_hours',
        ),
    ]
