# Generated by Django 3.2.8 on 2021-10-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20211016_0040'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='exercises',
        ),
        migrations.AlterModelTable(
            name='set',
            table='sets',
        ),
        migrations.AlterModelTable(
            name='workouts',
            table='workouts',
        ),
    ]
