# Generated by Django 5.2.6 on 2025-09-17 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_start_workout_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
